import Link from 'next/link';

export default function AdminHub() {
  return (
    <main className="page-shell" style={{ textAlign: 'center', paddingTop: '40px' }}>
      <h1 style={{ color: '#D4AF37', fontFamily: '"Cormorant Garamond", serif', fontSize: '2.5rem', marginBottom: '10px' }}>Royal Command Center</h1>
      <p style={{ color: '#aaa', marginBottom: '40px' }}>Select a module to manage.</p>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', maxWidth: '800px', margin: '0 auto', marginBottom: '40px' }}>
        <Link href="/admin/kitchen" style={{ textDecoration: 'none' }}><div style={{ backgroundColor: 'rgba(255,255,255,0.03)', padding: '30px', borderRadius: '12px', border: '1px solid rgba(229, 208, 143, 0.3)', backdropFilter: 'blur(10px)', transition: 'all 0.3s ease', cursor: 'pointer' }} onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(229, 208, 143, 0.1)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.6)'; }} onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.3)'; }}><span style={{ fontSize: '2.5rem', display: 'block', marginBottom: '10px' }}>👨‍🍳</span><h3 style={{ color: '#D4AF37', margin: '0', fontFamily: '"Cormorant Garamond", serif', fontSize: '1.3rem' }}>Kitchen Engine</h3><p style={{ color: '#aaa', fontSize: '0.8rem', margin: '5px 0 0 0' }}>Manage live orders</p></div></Link>
        
        <Link href="/admin/menu" style={{ textDecoration: 'none' }}><div style={{ backgroundColor: 'rgba(255,255,255,0.03)', padding: '30px', borderRadius: '12px', border: '1px solid rgba(229, 208, 143, 0.3)', backdropFilter: 'blur(10px)', transition: 'all 0.3s ease', cursor: 'pointer' }} onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(229, 208, 143, 0.1)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.6)'; }} onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.3)'; }}><span style={{ fontSize: '2.5rem', display: 'block', marginBottom: '10px' }}>📋</span><h3 style={{ color: '#D4AF37', margin: '0', fontFamily: '"Cormorant Garamond", serif', fontSize: '1.3rem' }}>Menu Manager</h3><p style={{ color: '#aaa', fontSize: '0.8rem', margin: '5px 0 0 0' }}>Add/Remove Food</p></div></Link>
        
        <Link href="/admin/vip" style={{ textDecoration: 'none' }}><div style={{ backgroundColor: 'rgba(255,255,255,0.03)', padding: '30px', borderRadius: '12px', border: '1px solid rgba(229, 208, 143, 0.3)', backdropFilter: 'blur(10px)', transition: 'all 0.3s ease', cursor: 'pointer' }} onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(229, 208, 143, 0.1)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.6)'; }} onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.3)'; }}><span style={{ fontSize: '2.5rem', display: 'block', marginBottom: '10px' }}>🎟️</span><h3 style={{ color: '#D4AF37', margin: '0', fontFamily: '"Cormorant Garamond", serif', fontSize: '1.3rem' }}>VIP Codes</h3><p style={{ color: '#aaa', fontSize: '0.8rem', margin: '5px 0 0 0' }}>Generate access passes</p></div></Link>
        
        <Link href="/admin/reservations" style={{ textDecoration: 'none' }}><div style={{ backgroundColor: 'rgba(255,255,255,0.03)', padding: '30px', borderRadius: '12px', border: '1px solid rgba(229, 208, 143, 0.3)', backdropFilter: 'blur(10px)', transition: 'all 0.3s ease', cursor: 'pointer' }} onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(229, 208, 143, 0.1)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.6)'; }} onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(229, 208, 143, 0.3)'; }}><span style={{ fontSize: '2.5rem', display: 'block', marginBottom: '10px' }}>📖</span><h3 style={{ color: '#D4AF37', margin: '0', fontFamily: '"Cormorant Garamond", serif', fontSize: '1.3rem' }}>Reservations</h3><p style={{ color: '#aaa', fontSize: '0.8rem', margin: '5px 0 0 0' }}>Guest list & check-in</p></div></Link>
      </div>
      
      <Link href="/" className="btn-secondary" style={{ display: 'inline-block', marginBottom: '40px', textDecoration: 'none' }}>← Return to Portal</Link>
    </main>
  );
}
